[project]
name = "custom-chatbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite==0.19.0",
    "alembic==1.13.1",
    "fastapi==0.109.2",
    "greenlet>=3.3.0",
    "httpx==0.27.0",
    "jinja2==3.1.3",
    "openai==1.12.0",
    "pydantic==2.6.1",
    "pydantic-settings==2.2.1",
    "python-dotenv==1.0.1",
    "sqlalchemy==2.0.27",
    "uvicorn[standard]==0.27.1",
]
